app = "streamverse-recommender"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[deploy]
  release_command = "python -m app"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1